- name: "Install and run uperf benchmark"
  hosts: all
  remote_user: root
  gather_facts: off
  tasks:
    - name: "Install and run uperf benchmark"
      include_role:
        name: uperf_benchmark
      vars:
        uperf_benchmark_host_active: foo.exampl.com
        uperf_benchmark_host_passive: bar.exampl.com
